import * as React from 'react';
import {
  useEffect,
  useState
} from 'react';

import {
  Icon,
  Spinner,
  SpinnerSize
} from '@fluentui/react';

import {
  getSP
} from '../../../pnpConfig';

import {
  IKpiMetricCardsProps
} from './IKpiMetricCardsProps';

interface IKpiData {
  total: number;
  pending: number;
  approved: number;
  actionRequired: number;
  highRisk: number;
}

interface IRawSharePointItem {
  Id?: number;
  [key: string]: unknown;
}

interface IResponseItem {
  id?: number;
  sharePointScore?: unknown;
}

interface IListConfiguration {
  title: string;
  percentageInternalName: string;
  qualifiedMinimum: number;
  conditionalMinimum: number;
}

interface IListFetchResult {
  listTitle: string;
  items: IResponseItem[];
  succeeded: boolean;
  errorMessage?: string;
}

interface IKpiCardConfiguration {
  key: keyof IKpiData;
  title: string;
  description: string;
  color: string;
  iconName: string;
  iconBackgroundColor: string;
  cardBackgroundColor: string;
  borderColor: string;
}

interface ICachedKpiData {
  data: IKpiData;
  cachedAt: number;
}

const EMPTY_KPI_DATA: IKpiData = {
  total: 0,
  pending: 0,
  approved: 0,
  actionRequired: 0,
  highRisk: 0
};

/**
 * Exact SharePoint score thresholds.
 *
 * Tier 1:
 * Qualified >= 10
 * Conditional >= 9.99 and < 10
 * High Risk < 9.99
 *
 * Tier 2:
 * Qualified >= 5
 * Conditional >= 4.99 and < 5
 * High Risk < 4.99
 *
 * Tier 3:
 * Qualified >= 2
 * Conditional >= 1.99 and < 2
 * High Risk < 1.99
 */
const DEFAULT_LIST_CONFIGURATIONS:
  readonly IListConfiguration[] = [
    {
      title:
        'CASSTECH_SSQ',

      percentageInternalName:
        'OverallQuestionsPercentage',

      qualifiedMinimum:
        10,

      conditionalMinimum:
        9.99
    },
    {
      title:
        'Tier 2 ESG Procurement Questionnaire',

      percentageInternalName:
        'OverallQuestionsPercentage',

      qualifiedMinimum:
        5,

      conditionalMinimum:
        4.99
    },
    {
      title:
        'Supplier Sustainability Questionnaires Tier 3',

      percentageInternalName:
        'OverallQuestionsPercentage',

      qualifiedMinimum:
        2,

      conditionalMinimum:
        1.99
    }
  ];

const KPI_CARDS:
  readonly IKpiCardConfiguration[] = [
    {
      key:
        'total',

      title:
        'Total Submissions',

      description:
        'All questionnaire tiers',

      color:
        '#1665a8',

      iconName:
        'TextDocument',

      iconBackgroundColor:
        '#e7f1fb',

      cardBackgroundColor:
        '#f6faff',

      borderColor:
        '#d9e9f8'
    },
    {
      key:
        'pending',

      title:
        'Pending ESG Review',

      description:
        'Score not yet available',

      color:
        '#9a6700',

      iconName:
        'Clock',

      iconBackgroundColor:
        '#fff1cc',

      cardBackgroundColor:
        '#fffaf1',

      borderColor:
        '#f7e6bd'
    },
    {
      key:
        'approved',

      title:
        'Approved by ESG',

      description:
        'Qualified suppliers',

      color:
        '#16833a',

      iconName:
        'Completed',

      iconBackgroundColor:
        '#e0f4e5',

      cardBackgroundColor:
        '#f5fbf6',

      borderColor:
        '#d5ecd9'
    },
    {
      key:
        'actionRequired',

      title:
        'Requires Procurement Action',

      description:
        'Conditionally qualified',

      color:
        '#c4314b',

      iconName:
        'ErrorBadge',

      iconBackgroundColor:
        '#fbe1e5',

      cardBackgroundColor:
        '#fff6f7',

      borderColor:
        '#f4d7dc'
    },
    {
      key:
        'highRisk',

      title:
        'High Risk Suppliers',

      description:
        'Not qualified',

      color:
        '#5c2d91',

      iconName:
        'ShieldAlert',

      iconBackgroundColor:
        '#eee5f8',

      cardBackgroundColor:
        '#faf7fd',

      borderColor:
        '#e4d9f1'
    }
  ];

/*
 * V9 prevents values generated by the previous normalized
 * 80%, 50%, and 20% KPI logic from being reused.
 */
const CACHE_VERSION:
  string = 'V9';

const CACHE_KEY_PREFIX:
  string =
    `SSQ_KPI_METRICS_DATA_${CACHE_VERSION}`;

const CACHE_TTL_MS:
  number =
    10 * 60 * 1000;

const getErrorMessage = (
  error: unknown
): string => {
  if (error instanceof Error) {
    return error.message;
  }

  return String(error);
};

const createCacheKeySegment = (
  value: string
): string => {
  return value
    .replace(
      /[^a-zA-Z0-9]/g,
      '_'
    )
    .substring(
      0,
      180
    );
};

const createCacheKey = (
  webUrl: string,
  configurations:
    readonly IListConfiguration[]
): string => {
  const configurationSegment:
    string =
      configurations
        .map(
          (
            configuration:
              IListConfiguration
          ): string => {
            return createCacheKeySegment(
              configuration.title
            );
          }
        )
        .join(
          '__'
        );

  return (
    `${CACHE_KEY_PREFIX}_` +
    `${createCacheKeySegment(webUrl)}_` +
    `${configurationSegment}`
  );
};

const isKpiData = (
  value: unknown
): value is IKpiData => {
  if (
    typeof value !== 'object' ||
    value === null
  ) {
    return false;
  }

  const candidate:
    Partial<IKpiData> =
      value as Partial<IKpiData>;

  return (
    typeof candidate.total === 'number' &&
    typeof candidate.pending === 'number' &&
    typeof candidate.approved === 'number' &&
    typeof candidate.actionRequired === 'number' &&
    typeof candidate.highRisk === 'number'
  );
};

const readCachedKpi = (
  cacheKey: string
): IKpiData | undefined => {
  try {
    const cachedJson:
      string | null =
        window.sessionStorage.getItem(
          cacheKey
        );

    if (!cachedJson) {
      return undefined;
    }

    const cachedValue:
      ICachedKpiData =
        JSON.parse(
          cachedJson
        ) as ICachedKpiData;

    if (
      !cachedValue ||
      typeof cachedValue.cachedAt !== 'number' ||
      !isKpiData(cachedValue.data)
    ) {
      window.sessionStorage.removeItem(
        cacheKey
      );

      return undefined;
    }

    const cacheAge:
      number =
        Date.now() -
        cachedValue.cachedAt;

    if (
      cacheAge > CACHE_TTL_MS
    ) {
      window.sessionStorage.removeItem(
        cacheKey
      );

      return undefined;
    }

    return cachedValue.data;
  } catch (error: unknown) {
    console.warn(
      '[Supplier ESG KPI] Unable to read cached KPI data.',
      error
    );

    return undefined;
  }
};

const writeCachedKpi = (
  cacheKey: string,
  data: IKpiData
): void => {
  try {
    const cachedValue:
      ICachedKpiData = {
        data,
        cachedAt:
          Date.now()
      };

    window.sessionStorage.setItem(
      cacheKey,
      JSON.stringify(
        cachedValue
      )
    );
  } catch (error: unknown) {
    console.warn(
      '[Supplier ESG KPI] Unable to cache KPI data.',
      error
    );
  }
};

/**
 * Parses the exact numeric value returned by SharePoint.
 *
 * The method removes visual formatting such as "%" and
 * decimal commas, but does not normalize, divide, multiply,
 * or otherwise change the numeric scale.
 *
 * Examples:
 * "10%"   -> 10
 * "9.99%" -> 9.99
 * "5%"    -> 5
 * "4.99%" -> 4.99
 * "2%"    -> 2
 * "1.99%" -> 1.99
 */
const parseExactSharePointScore = (
  value: unknown
): number | undefined => {
  if (
    value === null ||
    value === undefined ||
    value === ''
  ) {
    return undefined;
  }

  if (
    typeof value === 'number'
  ) {
    return (
      isFinite(value) &&
      value >= 0
    )
      ? value
      : undefined;
  }

  if (
    typeof value !== 'string'
  ) {
    return undefined;
  }

  const normalizedValue:
    string =
      value
        .replace(
          /%/g,
          ''
        )
        .replace(
          ',',
          '.'
        )
        .trim();

  if (
    !normalizedValue
  ) {
    return undefined;
  }

  const parsedValue:
    number =
      parseFloat(
        normalizedValue
      );

  if (
    isNaN(parsedValue) ||
    !isFinite(parsedValue) ||
    parsedValue < 0
  ) {
    return undefined;
  }

  return parsedValue;
};

const getListConfigurations = (
  props: IKpiMetricCardsProps
): readonly IListConfiguration[] => {
  return [
    {
      ...DEFAULT_LIST_CONFIGURATIONS[0],

      title:
        props.tier1ListTitle?.trim() ||
        DEFAULT_LIST_CONFIGURATIONS[0].title
    },
    {
      ...DEFAULT_LIST_CONFIGURATIONS[1],

      title:
        props.tier2ListTitle?.trim() ||
        DEFAULT_LIST_CONFIGURATIONS[1].title
    },
    {
      ...DEFAULT_LIST_CONFIGURATIONS[2],

      title:
        props.tier3ListTitle?.trim() ||
        DEFAULT_LIST_CONFIGURATIONS[2].title
    }
  ];
};

const fetchListItems = async (
  props: IKpiMetricCardsProps,
  configuration: IListConfiguration
): Promise<IListFetchResult> => {
  try {
    const sp =
      getSP(
        props.context
      );

    const rawItems:
      IRawSharePointItem[] =
        await sp.web.lists
          .getByTitle(
            configuration.title
          )
          .items
          .select(
            'Id',
            configuration
              .percentageInternalName
          )
          .top(
            5000
          )() as IRawSharePointItem[];

    const items:
      IResponseItem[] =
        rawItems.map(
          (
            item:
              IRawSharePointItem
          ): IResponseItem => {
            return {
              id:
                typeof item.Id === 'number'
                  ? item.Id
                  : undefined,

              sharePointScore:
                item[
                  configuration
                    .percentageInternalName
                ]
            };
          }
        );

    return {
      listTitle:
        configuration.title,

      items,

      succeeded:
        true
    };
  } catch (error: unknown) {
    const errorMessage:
      string =
        getErrorMessage(
          error
        );

    console.error(
      '[Supplier ESG KPI] Unable to retrieve list items.',
      {
        listTitle:
          configuration.title,

        error:
          errorMessage
      }
    );

    return {
      listTitle:
        configuration.title,

      items:
        [],

      succeeded:
        false,

      errorMessage
    };
  }
};

const calculateKpiData = (
  results:
    readonly IListFetchResult[],

  configurations:
    readonly IListConfiguration[]
): IKpiData => {
  const calculatedData:
    IKpiData = {
      total:
        0,

      pending:
        0,

      approved:
        0,

      actionRequired:
        0,

      highRisk:
        0
    };

  results.forEach(
    (
      result:
        IListFetchResult,

      index:
        number
    ): void => {
      if (
        !result.succeeded
      ) {
        return;
      }

      const configuration:
        IListConfiguration =
          configurations[index];

      result.items.forEach(
        (
          item:
            IResponseItem
        ): void => {
          calculatedData.total += 1;

          const exactScore:
            number | undefined =
              parseExactSharePointScore(
                item.sharePointScore
              );

          /*
           * A submission with no valid SharePoint score is pending.
           */
          if (
            exactScore === undefined
          ) {
            calculatedData.pending += 1;
            return;
          }

          /*
           * Exact SharePoint score meets the qualified threshold.
           */
          if (
            exactScore >=
            configuration.qualifiedMinimum
          ) {
            calculatedData.approved += 1;
            return;
          }

          /*
           * Exact SharePoint score meets the conditional threshold.
           */
          if (
            exactScore >=
            configuration.conditionalMinimum
          ) {
            calculatedData.actionRequired += 1;
            return;
          }

          /*
           * Exact SharePoint score is below the conditional threshold.
           */
          calculatedData.highRisk += 1;
        }
      );
    }
  );

  const classifiedTotal:
    number =
      calculatedData.pending +
      calculatedData.approved +
      calculatedData.actionRequired +
      calculatedData.highRisk;

  console.info(
    '[Supplier ESG KPI validation]',
    {
      total:
        calculatedData.total,

      classified:
        classifiedTotal,

      isBalanced:
        calculatedData.total ===
        classifiedTotal,

      details:
        calculatedData
    }
  );

  return calculatedData;
};

const wrapperStyle:
  React.CSSProperties = {
    boxSizing:
      'border-box',

    width:
      '100%',

    minWidth:
      0,

    fontFamily: "'Figtree', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
  };

const containerStyle:
  React.CSSProperties = {
    display:
      'grid',

    gridTemplateColumns:
      'repeat(auto-fit, minmax(250px, 1fr))',

    gap:
      '10px',

    boxSizing:
      'border-box',

    width:
      '100%',

    minWidth:
      0,  
  };

const cardStyle:
  React.CSSProperties = {
    display:
      'flex',

    boxSizing:
      'border-box',

    width:
      '100%',

    minWidth:
      0,

    minHeight:
      '130px',

    alignItems:
      'center',

    gap:
      '14px',

    padding:
      '18px 16px',

    borderStyle:
      'solid',

    borderWidth:
      '1px',

    borderRadius:
      '10px',

    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.06)',
  };

const iconContainerStyle:
  React.CSSProperties = {
    display:
      'inline-flex',

    width:
      '52px',

    height:
      '52px',

    flex:
      '0 0 52px',

    alignItems:
      'center',

    justifyContent:
      'center',

    borderRadius:
      '50%'
  };

const valueStyle:
  React.CSSProperties = {
    minWidth:
      '32px',

    color:
      '#201f1e',

    fontSize:
      '26px',

    fontWeight:
      600,

    lineHeight:
      1,

    fontVariantNumeric:
      'tabular-nums'
  };

const textContainerStyle:
  React.CSSProperties = {
    display:
      'flex',

    minWidth:
      0,

    flex:
      '1 1 auto',

    flexDirection:
      'column',

    justifyContent:
      'center'
  };

const titleStyle:
  React.CSSProperties = {
    margin:
      0,

    color:
      '#201f1e',

    fontSize:
      '18px',

    fontWeight:
      600,
  };

const descriptionStyle:
  React.CSSProperties = {
    marginTop:
      '4px',

    color:
      '#605e5c',

    fontSize:
      '12px',

    fontWeight:
      400,
  };

const loadingStyle:
  React.CSSProperties = {
    boxSizing:
      'border-box',

    width:
      '100%',

    padding:
      '18px',

    color:
      '#605e5c',

    fontFamily: "'Figtree', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
  };

const warningStyle:
  React.CSSProperties = {
    boxSizing:
      'border-box',

    width:
      '100%',

    marginBottom:
      '14px',

    padding:
      '10px 14px',

    color:
      '#8a6d1d',

    backgroundColor:
      '#fff4ce',

    border:
      '1px solid #f4d780',

    borderRadius:
      '6px',

    fontSize:
      '13px',

    lineHeight:
      '19px'
  };

export function KpiMetricCards(
  props: IKpiMetricCardsProps
): React.ReactElement {
  const [
    kpi,
    setKpi
  ] =
    useState<IKpiData>(
      EMPTY_KPI_DATA
    );

  const [
    loading,
    setLoading
  ] =
    useState<boolean>(
      true
    );

  const [
    errorMessage,
    setErrorMessage
  ] =
    useState<string>(
      ''
    );

  useEffect(
    (): (() => void) => {
      let isMounted:
        boolean =
          true;

      const loadKpiData =
        async (): Promise<void> => {
          const configurations:
            readonly IListConfiguration[] =
              getListConfigurations(
                props
              );

          const webUrl:
            string =
              props.context
                .pageContext
                .web
                .absoluteUrl;

          const cacheKey:
            string =
              createCacheKey(
                webUrl,
                configurations
              );

          const cachedData:
            IKpiData | undefined =
              readCachedKpi(
                cacheKey
              );

          if (
            cachedData &&
            isMounted
          ) {
            setKpi(
              cachedData
            );

            setLoading(
              false
            );
          } else if (
            isMounted
          ) {
            setLoading(
              true
            );
          }

          try {
            const results:
              IListFetchResult[] =
                await Promise.all(
                  configurations.map(
                    (
                      configuration:
                        IListConfiguration
                    ): Promise<IListFetchResult> => {
                      return fetchListItems(
                        props,
                        configuration
                      );
                    }
                  )
                );

            if (
              !isMounted
            ) {
              return;
            }

            const successfulResults:
              IListFetchResult[] =
                results.filter(
                  (
                    result:
                      IListFetchResult
                  ): boolean => {
                    return result.succeeded;
                  }
                );

            const failedResults:
              IListFetchResult[] =
                results.filter(
                  (
                    result:
                      IListFetchResult
                  ): boolean => {
                    return !result.succeeded;
                  }
                );

            if (
              successfulResults.length === 0
            ) {
              setKpi(
                EMPTY_KPI_DATA
              );

              setErrorMessage(
                'KPI metrics could not be loaded from ' +
                'the configured SharePoint lists.'
              );

              return;
            }

            const calculatedData:
              IKpiData =
                calculateKpiData(
                  results,
                  configurations
                );

            setKpi(
              calculatedData
            );

            writeCachedKpi(
              cacheKey,
              calculatedData
            );

            if (
              failedResults.length > 0
            ) {
              const failedTitles:
                string =
                  failedResults
                    .map(
                      (
                        result:
                          IListFetchResult
                      ): string => {
                        return result.listTitle;
                      }
                    )
                    .join(
                      ', '
                    );

              setErrorMessage(
                'Some KPI sources could not be loaded: ' +
                `${failedTitles}. Metrics shown are partial.`
              );
            } else {
              setErrorMessage(
                ''
              );
            }
          } catch (
            error:
              unknown
          ) {
            console.error(
              '[Supplier ESG KPI] Unexpected KPI loading error.',
              error
            );

            if (
              isMounted
            ) {
              setErrorMessage(
                'An unexpected error occurred while ' +
                'loading the supplier ESG KPI metrics.'
              );
            }
          } finally {
            if (
              isMounted
            ) {
              setLoading(
                false
              );
            }
          }
        };

      loadKpiData()
        .catch(
          (
            error:
              unknown
          ): void => {
            console.error(
              '[Supplier ESG KPI] Unhandled KPI loading error.',
              error
            );

            if (
              isMounted
            ) {
              setLoading(
                false
              );

              setErrorMessage(
                'An unexpected error occurred while ' +
                'loading the supplier ESG KPI metrics.'
              );
            }
          }
        );

      return (): void => {
        isMounted =
          false;
      };
    },
    [
      props.context,
      props.tier1ListTitle,
      props.tier2ListTitle,
      props.tier3ListTitle
    ]
  );

  if (
    loading
  ) {
    return (
      <div
        role="status"
        aria-live="polite"
        style={loadingStyle}
      >
        <Spinner
          size={SpinnerSize.small}
          label="Loading supplier ESG KPI metrics"
        />
      </div>
    );
  }

  return (
    <section
      style={wrapperStyle}
      aria-label="Supplier ESG KPI metrics"
    >
      {errorMessage && (
        <div
          role="alert"
          style={warningStyle}
        >
          {errorMessage}
        </div>
      )}

      <div style={containerStyle}>
        {KPI_CARDS.map(
          (
            card:
              IKpiCardConfiguration
          ): React.ReactElement => {
            return (
              <article
                key={card.key}
                style={{
                  ...cardStyle,

                  color:
                    card.color,

                  backgroundColor:
                    card.cardBackgroundColor,

                  borderColor:
                    card.borderColor
                }}
                aria-label={
                  `${card.title}: ` +
                  `${kpi[card.key].toString()}`
                }
              >
                <div
                  style={{
                    ...iconContainerStyle,

                    color:
                      card.color,

                    backgroundColor:
                      card.iconBackgroundColor
                  }}
                  aria-hidden="true"
                >
                  <Icon
                    iconName={
                      card.iconName
                    }
                    styles={{
                      root: {
                        color:
                          card.color,

                        fontSize:
                          '36px',

                        lineHeight:
                          '36px'
                      }
                    }}
                  />
                </div>

                <strong style={valueStyle}>
                  {kpi[card.key]}
                </strong>

                <div style={textContainerStyle}>
                  <h3 style={titleStyle}>
                    {card.title}
                  </h3>

                  <span style={descriptionStyle}>
                    {card.description}
                  </span>
                </div>
              </article>
            );
          }
        )}
      </div>
    </section>
  );
}

export default KpiMetricCards;